spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: appdev
##    url: jdbc:mysql://172.18.3.77:3306/db_banulp
#    url: jdbc:mysql://172.18.3.77:3306/gdadmin
#    password: appdev01
  r2dbc:
#    url: r2dbcs:mariadb://172.18.3.77:3306/gdadmin?sslMode=DISABLED&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    url: r2dbcs:mariadb://172.18.3.77:3306/db_banulp?sslMode=DISABLED&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: appdev
    password: appdev01
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#https://spring.io/guides/gs/accessing-data-mysql/
#https://www.baeldung.com/hibernate-one-to-many
#https://heesutory.tistory.com/34
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
#        http://localhost:8080/demo/init